
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ipbd_sms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  typeAliasesPackage: com.ipbd.ipbdsms.entity
  mapper-locations: classpath:mybatis/*.xml
# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml

logging:
  file:
    name: log/log.log
    level:
      root: info
      com.sign: debug